version: '3'
services:
  pelican-sitebuilder:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8000"
    volumes:
      - .:/app
    environment:
      - CONFFILE=pelicanconf.py
      - SITEURL=http://localhost:8080
    stdin_open: true
    tty: true
