name: Pelican site CI

on:
  schedule:
    - cron: '0 0 * * *' # Once per day at midnight
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: josemlp91/gh-pages-pelican-action@uv
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        GH_PAGES_CNAME: ${{secrets.GH_PAGES_CNAME || 'none'}}
        GOOGLE_ANALYTICS_CODE: ${{secrets.GOOGLE_ANALYTICS_CODE || '0000'}}
        SITEURL: ${{secrets.SITEURL}}
